### PR TITLE
Unusable

### PR DESCRIPTION
**Pull request by ghost**
It uses new Reddit website. Real ricers use old Reddit.

P. S. : I made small changes to CSS.

### CODE REVIEW

**Comment by elkowar** [comment]
if you do changes to the styling of a website, please include some screenshots highlighting the before and after, so we can more easily evaluate the aesthetics.

**Comment by ghost** [comment]
The difference is not massive. I kept the same modern and slim look. I changed the font of the list to Open Sans because it looks more professional. Also I changed the color of the box to a lighter black, so the contrast is higher and added a left margin to the paragraph.

**Comment by ghost** [comment]
Unixporn
I forgot to add the image.

**Comment by sophec** [comment]
I would strongly advise against adding links to old.reddit. The entire purpose of the unixporn community is user choice and customization. If the user wants old reddit, they can set that in their user settings and reddit.com links will take them to old reddit. If they want new reddit, however, it's pointless of us to be linking them to the old one.

**Comment by ghost** [comment]
I change it to new Reddit.

**Comment by eepykate** [comment]
oh, didnt even see this pr

this also looks like a hacktober PR, but it's not on a hacktoberfest repo so lol

**Comment by eepykate** [comment]
It doesn't use old reddit, it uses your default reddit design.

You do not need for shove your favorite font down our throats, let the user choose their own, if you select one you don't like in your browser, that is completely your fault.

also what, "fantasy" font style? sounds like the kind of font samsung phones come with - in the worst way possible.

**Comment by eepykate** [comment]
Also, why did you change the colours? They're from the logo, I highly doubt the new colours you chose are from there too. We also use that colour set in other places too.

**Pull request closed without merging**
