### PR TITLE
.

### PR DESCRIPTION
**Pull request by ghost**
.

### CODE REVIEW

**Comment by eepykate** [comment]
I'm *really* not a fan of the underlines, as well as the italics, as well as the behavior changes with links.  Unless it's an image or you're on a bloated webapp (discord) links should act like links.  If you want to open in a new tab, use ctrl-click / middleclick.

**Comment by ziadomalik** [comment]
Alright look, removed all that, but at least wanna keep the logo?

**Comment by eepykate** [comment]
I guess the logo is fine, but again, I'm not a fan of making it all... flat - ie removing the alignment.  

also you completely broke small screens (such as mobile).

image

**Comment by ziadomalik** [comment]
Alright, I understand

**Comment by eepykate** [comment]
:pensive: apologies, I'm very picky about some stuff.

**Comment by ziadomalik** [comment]
no worries, l see that as an opportunity to improve. It is your full right to be picky.

**Comment by eepykate** [comment]
I mean, if it's any consolation it does kinda hurt turning down your changes when you're just trying to help.

**Comment by ziadomalik** [comment]
The day will come where you merge that bad boi into the main branch I'm telling you, I just need a couple of tries😆

**Comment by eepykate** [comment]
Fwiw, I do like the idea of having the logo visible as well as the main header to the left.  If you want you can re-open this PR with just those changes.

I don't mind the idea of something like this (the position was hard-coded so i won't bother sharing code since it was a hackjob)
image

or this, which is much closer to your proposal
image

(also please use tabs instead of spaces.)

**Comment by ziadomalik** [comment]
Alright, did both variants. (not hardcoded). Both snippets are in the code. Delete the version you wont end up with.
I'll make a new pull request because I deleted the fork for some reason.

**Pull request closed without merging**
